const constructionData = {
  "se": [
    "Vi gjuter plattan med betong imorgon.",
    "Regla med regelvirke.",
    "Vi väntar på armeringsjärn.",
    "Spackla med finspackel.",
    "Fixa fika med termos.",
    "Bär hjälm med hakband.",
    "Släck motorn på grävmaskinen.",
    "Hissa upp gipsskivor med kranen.",
    "Pass på ställningen med rör.",
    "Lägg råspont på takstolarna.",
    "Dra på flytspackel.",
    "Regla med regelvirke här.",
    "Betongen är för blöt.",
    "Mät med lasersax.",
    "Fäst OSB-skivor med spikpistol.",
    "Lägg glespanel bakom gips.",
    "Dra inte hårt i förlängningssladden.",
    "Vi tar lunch med matlåda.",
    "Vem har min vattenpass?",
    "Kontrollera fallskyddet innan du klättrar.",
    "Isolera med mineralull.",
    "Dra åt bultarna med momentnyckel.",
    "Vänta på provtryckning av rör.",
    "Stäng av strömmen med brytare.",
    "Lägg underlagspapp på taket.",
    "Skruva fast plåten med skruv.",
    "Montera fönster med karmhylsor.",
    "Spruta fogskum med pistol.",
    "Lägg markduk under gruset.",
    "Rensa formen med tryckluft.",
    "Använd armeringsnät i plattan.",
    "Skär gips med kniv.",
    "Fäst takpannor med stormkrok.",
    "Dra kabel i VP-rör.",
    "Gjut sockel med betong.",
    "Montera dörr med gångjärn.",
    "Lägg dräneringsrör med filterduk.",
    "Använd slipmaskin.",
    "Måla med akrylatfärg.",
    "Fäst plåtbeslag med popnit.",
    "Lägg cellplast under plattan.",
    "Skruva med skruvdragare.",
    "Montera ventilation med FTX-system.",
    "Använd hörselkåpor.",
    "Gjut trappa med armering.",
    "Fäst list med dykertpistol.",
    "Lägg taktegel på taket.",
    "Dra fiber med blåsrör.",
    "Isolera rör med rörisolering.",
    "Använd andningsskydd.",
    "Montera fönsterbleck av plåt.",
    "Skär isolering med isolerkniv.",
    "Lägg markvärme med rör.",
    "Fäst takfotsplåt med skruv.",
    "Gjut pelare med betong.",
    "Använd laser.",
    "Montera brandtätning.",
    "Dra jordkabel i markrör.",
    "Lägg diffusionsspärr på taket.",
    "Fäst med spikpistol.",
    "Gjut bjälklag med armering.",
    "Använd skyddsglasögon.",
    "Montera dörrstopp.",
    "Skär plåt med plåtsax.",
    "Lägg dräneringsmatta.",
    "Dra kabel i rör.",
    "Isolera vind med mineralull.",
    "Fäst med skruv.",
    "Montera sprinklersystem.",
    "Använd knäskydd.",
    "Gjut kantbalk med betong.",
    "Skär gips med gipssax.",
    "Lägg takpapp.",
    "Dra fiber med blåsmaskin.",
    "Isolera golv med cellplast.",
    "Fäst med dykert.",
    "Montera fönster med bleck.",
    "Använd slipmaskin.",
    "Gjut grund med betong.",
    "Skär isolering med kniv.",
    "Lägg markduk under makadam.",
    "Dra kabel i rör.",
    "Montera branddörr.",
    "Fäst med spikpistol.",
    "Gjut trappa med armering.",
    "Använd hörselskydd.",
    "Lägg taktegel.",
    "Dra jordfelsbrytare.",
    "Isolera vägg med mineralull.",
    "Fäst med skruvdragare.",
    "Montera FTX-aggregat.",
    "Skär plåt med nibbler.",
    "Lägg dräneringsrör.",
    "Dra fiber med dragfjäder.",
    "Gjut pelare med betong.",
    "Använd laser.",
    "Montera brandtätning.",
    "Fäst med popnitpistol.",
    "Lägg vindskydd.",
    "Kontrollera moment med momentnyckel."
  ],
  "no": [
    "Vi støper sålen med betong i morgen.",
    "Regel med trykkimpregnert virke.",
    "Vi venter på armeringsjern.",
    "Sparkle med finsparkel.",
    "Fiks matpause med termos.",
    "Bruk hjelm med hakestropp.",
    "Slå av motoren på gravemaskinen.",
    "Heis opp gipsplater med kran.",
    "Pass på stillaset med rør.",
    "Legg råspont på takstoler.",
    "Hell flytsparkel.",
    "Regel med virke her.",
    "Betongen er for våt.",
    "Mål med laser.",
    "Fest OSB med spikerpistol.",
    "Legg gips bak gips.",
    "Ikke dra hardt i skjøteledningen.",
    "Vi tar lunsj med matboks.",
    "Hvem har vateret mitt?",
    "Sjekk fallsikringen før klatring.",
    "Isoler med mineralull.",
    "Stram boltene med momentnøkkel.",
    "Vent på trykktesting av rør.",
    "Slå av strømmen med bryter.",
    "Legg undertakspapp på taket.",
    "Skru platen med skru.",
    "Monter vindu med karmhylser.",
    "Spray fugeskum med pistol.",
    "Legg markduk under grusen.",
    "Rengjør form med trykkluft.",
    "Bruk armeringsnett i sålen.",
    "Skjær gips med kniv.",
    "Fest takstein med stormkrok.",
    "Trekk kabel i VP-rør.",
    "Støp sokkel med betong.",
    "Monter dør med hengsler.",
    "Legg dreneringsrør med filterduk.",
    "Bruk slipemaskin.",
    "Mal med akrylmaling.",
    "Fest blikkbeslag med popnagle.",
    "Legg isopor under sålen.",
    "Skru med skrutrekker.",
    "Monter ventilasjon med FTX-system.",
    "Bruk hørselvern.",
    "Støp trapp med armering.",
    "Fest list med dykkertpistol.",
    "Legg takstein på taket.",
    "Trekk fiber med blåserør.",
    "Isoler rør med rørisolasjon.",
    "Bruk åndedrettsvern.",
    "Monter vindusbeslag av blikk.",
    "Skjær isolasjon med isolasjonskniv.",
    "Legg gulvvarme med rør.",
    "Fest takfotsblikk med skru.",
    "Støp søyle med betong.",
    "Bruk laser.",
    "Monter branntetting.",
    "Trekk jordkabel i markrør.",
    "Legg diffusjonssperre på taket.",
    "Fest med spikerpistol.",
    "Støp bjelkelag med armering.",
    "Bruk vernebriller.",
    "Monter dørstopper.",
    "Skjær blikk med blikk saks.",
    "Legg dreneringsmatte.",
    "Trekk kabel i rør.",
    "Isoler loft med mineralull.",
    "Fest med skru.",
    "Monter sprinkleranlegg.",
    "Bruk knebeskyttelse.",
    "Støp kantbjelke med betong.",
    "Skjær gips med gipssaks.",
    "Legg takpapp.",
    "Trekk fiber med blåsemaskin.",
    "Isoler gulv med isopor.",
    "Fest med dykkert.",
    "Monter vindu med beslag.",
    "Bruk slipemaskin.",
    "Støp grunnmur med betong.",
    "Skjær isolasjon med kniv.",
    "Legg markduk under singel.",
    "Trekk kabel i rør.",
    "Monter branndør.",
    "Fest med spikerpistol.",
    "Støp trapp med armering.",
    "Bruk hørselvern.",
    "Legg takstein.",
    "Trekk jordfeilbryter.",
    "Isoler vegg med mineralull.",
    "Fest med skrutrekker.",
    "Monter FTX-aggregat.",
    "Skjær blikk med nibbler.",
    "Legg dreneringsrør.",
    "Trekk fiber med trekkfjær.",
    "Støp søyle med betong.",
    "Bruk laser.",
    "Monter branntetting.",
    "Fest med popnaglepistol.",
    "Legg vindsperre.",
    "Kontroller moment med momentnøkkel."
  ],
  "da": [
    "Vi støber sålen med beton i morgen.",
    "Reglar med trykimprægneret træ.",
    "Vi venter på armeringsjern.",
    "Spatle med finspartel.",
    "Fik madpause med termokande.",
    "Brug hjelm med hakestropp.",
    "Sluk motoren på gravemaskinen.",
    "Hejs op gipsplader med kran.",
    "Pas på stilladset med rør.",
    "Læg råspont på tagspær.",
    "Hæld flydespartel.",
    "Reglar med træ her.",
    "Betonen er for våd.",
    "Mål med laser.",
    "Fastgør OSB med spikerpistol.",
    "Læg gips bag gips.",
    "Træk ikke hårdt i forlængerkablet.",
    "Vi tager frokost med madkasse.",
    "Hvem har mit vaterpas?",
    "Tjek faldsikring før klatring.",
    "Isoler med mineraluld.",
    "Spænd boltene med momentnøgle.",
    "Vent på trykprøve af rør.",
    "Sluk strømmen med afbryder.",
    "Læg undertagspapir på taget.",
    "Skru pladen med skrue.",
    "Montér vindue med karmhylster.",
    "Sprøjt fugeskum med pistol.",
    "Læg markdug under gruset.",
    "Rens form med trykluft.",
    "Brug armeringsnet i sålen.",
    "Skær gips med kniv.",
    "Fastgør tagsten med stormkrog.",
    "Træk kabel i VP-rør.",
    "Støb sokkel med beton.",
    "Montér dør med hængsler.",
    "Læg drænrør med filterdug.",
    "Brug slibemaskine.",
    "Mal med akrylmaling.",
    "Fastgør blikbeslag med popnitte.",
    "Læg flamingo under sålen.",
    "Skru med skruetrækker.",
    "Montér ventilation med FTX-system.",
    "Brug høreværn.",
    "Støb trappe med armering.",
    "Fastgør liste med dykkerpistol.",
    "Læg tagsten på taget.",
    "Træk fiber med blæserør.",
    "Isoler rør med rørisolering.",
    "Brug åndedrætsværn.",
    "Montér vinduesbeslag af blik.",
    "Skær isolering med isoleringskniv.",
    "Læg gulvvarme med rør.",
    "Fastgør tagfodsblik med skrue.",
    "Støb søjle med beton.",
    "Brug laser.",
    "Montér brandtætning.",
    "Træk jordkabel i markrør.",
    "Læg diffusionsspærre på taget.",
    "Fastgør med spikerpistol.",
    "Støb bjælkelag med armering.",
    "Brug sikkerhedsbriller.",
    "Montér dørstopper.",
    "Skær blik med bliksaks.",
    "Læg drænmåtte.",
    "Træk kabel i rør.",
    "Isoler loft med mineraluld.",
    "Fastgør med skrue.",
    "Montér sprinkleranlæg.",
    "Brug knæbeskyttelse.",
    "Støb kantbjælke med beton.",
    "Skær gips med gipssaks.",
    "Læg tagpap.",
    "Træk fiber med blæsemaskine.",
    "Isoler gulv med flamingo.",
    "Fastgør med dykker.",
    "Montér vindue med beslag.",
    "Brug slibemaskine.",
    "Støb fundament med beton.",
    "Skær isolering med kniv.",
    "Læg markdug under singel.",
    "Træk kabel i rør.",
    "Montér branddør.",
    "Fastgør med spikerpistol.",
    "Støb trappe med armering.",
    "Brug høreværn.",
    "Læg tagsten.",
    "Træk fejlstrømsafbryder.",
    "Isoler væg med mineraluld.",
    "Fastgør med skruetrækker.",
    "Montér FTX-aggregat.",
    "Skær blik med nibbler.",
    "Læg drænrør.",
    "Træk fiber med trækfjedre.",
    "Støb søjle med beton.",
    "Brug laser.",
    "Montér brandtætning.",
    "Fastgør med popnittepistol.",
    "Læg vindspærre.",
    "Kontrollér moment med momentnøgle."
  ],
  "de": [
    "Wir gießen die Bodenplatte mit Beton morgen.",
    "Ständer mit Kantholz.",
    "Wir warten auf Bewehrung.",
    "Spachtel mit Feinspachtel.",
    "Pause mit Thermoskanne.",
    "Helm mit Kinnriemen tragen.",
    "Motor aus beim Bagger.",
    "Hängen Gipskartonplatten mit Kran hoch.",
    "Pass auf Gerüst mit Rohren auf.",
    "Legen Rohspanplatten auf Dachstuhl.",
    "Gießen Estrich.",
    "Ständer mit Holz hier.",
    "Beton ist zu nass.",
    "Messen mit Laser.",
    "Befestigen OSB mit Nagelpistole.",
    "Legen Lattung hinter Gips.",
    "Nicht hart an Verlängerungskabel ziehen.",
    "Wir machen Mittag mit Brotdose.",
    "Wer hat meine Wasserwaage?",
    "Kontrolliere Absturzsicherung vor Klettern.",
    "Dämmen mit Mineralwolle.",
    "Anziehen Schrauben mit Drehmomentschlüssel.",
    "Warten auf Druckprüfung von Rohren.",
    "Strom abschalten mit Schalter.",
    "Legen Unterdeckbahn auf Dach.",
    "Schrauben Blech mit Schraube.",
    "Montieren Fenster mit Karmschrauben.",
    "Sprühen Montageschaum mit Pistole.",
    "Legen Geotextil unter Kies.",
    "Reinigen Schalung mit Druckluft.",
    "Verwenden Bewehrungsmatte in Platte.",
    "Schneiden Gips mit Messer.",
    "Befestigen Dachziegel mit Sturmhaken.",
    "Ziehen Kabel in VP-Rohr.",
    "Gießen Sockel mit Beton.",
    "Montieren Tür mit Scharnieren.",
    "Legen Dränrohr mit Filtervlies.",
    "Verwenden Schleifmaschine.",
    "Streichen mit Acrylfarbe.",
    "Befestigen Blechbesatz mit Blindniete.",
    "Legen Dämmplatten unter Platte.",
    "Schrauben mit Akkuschrauber.",
    "Montieren Lüftung mit FTX-System.",
    "Verwenden Gehörschutz.",
    "Gießen Treppe mit Bewehrung.",
    "Befestigen Leiste mit Stiftpistole.",
    "Legen Dachziegel auf Dach.",
    "Ziehen Glasfaser mit Blasrohr.",
    "Dämmen Rohre mit Rohrisolierung.",
    "Verwenden Atemschutz.",
    "Montieren Fensterblech aus Blech.",
    "Schneiden Dämmung mit Dämmstoffmesser.",
    "Legen Fußbodenheizung mit Rohren.",
    "Befestigen Traufblech mit Schraube.",
    "Gießen Stütze mit Beton.",
    "Verwenden Laser.",
    "Montieren Brandschutz.",
    "Ziehen Erdkabel in Erdrohr.",
    "Legen Dampfsperre auf Dach.",
    "Befestigen mit Nagelpistole.",
    "Gießen Decke mit Bewehrung.",
    "Verwenden Schutzbrille.",
    "Montieren Türstopper.",
    "Schneiden Blech mit Blechschere.",
    "Legen Dränmatte.",
    "Ziehen Kabel in Rohr.",
    "Dämmen Dach mit Mineralwolle.",
    "Befestigen mit Schraube.",
    "Montieren Sprinkleranlage.",
    "Verwenden Knieschoner.",
    "Gießen Randbalken mit Beton.",
    "Schneiden Gips mit Gipsscheere.",
    "Legen Dachpappe.",
    "Ziehen Glasfaser mit Blasmachine.",
    "Dämmen Boden mit Dämmplatten.",
    "Befestigen mit Stift.",
    "Montieren Fenster mit Blech.",
    "Verwenden Schleifmaschine.",
    "Gießen Fundament mit Beton.",
    "Schneiden Dämmung mit Messer.",
    "Legen Geotextil unter Schotter.",
    "Ziehen Kabel in Rohr.",
    "Montieren Brandschutztür.",
    "Befestigen mit Nagelpistole.",
    "Gießen Treppe mit Bewehrung.",
    "Verwenden Gehörschutz.",
    "Legen Dachziegel.",
    "Ziehen FI-Schalter.",
    "Dämmen Wand mit Mineralwolle.",
    "Befestigen mit Akkuschrauber.",
    "Montieren FTX-Aggregat.",
    "Schneiden Blech mit Nibbler.",
    "Legen Dränrohr.",
    "Ziehen Glasfaser mit Zugfeder.",
    "Gießen Stütze mit Beton.",
    "Verwenden Laser.",
    "Montieren Brandschutz.",
    "Befestigen mit Blindnietpistole.",
    "Legen Windsperre.",
    "Kontrollieren Drehmoment mit Drehmomentschlüssel."
  ],
  "nl": [
    "We storten de fundering met beton morgen.",
    "Regels met geïmpregneerd hout.",
    "We wachten op wapeningsstaal.",
    "Stuc met fijnpleister.",
    "Pauze met thermoskan.",
    "Helm met kinband dragen.",
    "Motor uit bij de graafmachine.",
    "Hijs gipsplaten met kraan.",
    "Let op steiger met buizen.",
    "Leggen ruwe platen op dakspanten.",
    "Giet vloeipleister.",
    "Regels met hout hier.",
    "Beton is te nat.",
    "Meten met laser.",
    "Bevestigen OSB met spijkerpistool.",
    "Leggen latten achter gips.",
    "Niet hard trekken aan verlengkabel.",
    "We nemen lunch met broodtrommel.",
    "Wie heeft mijn waterpas?",
    "Controleer valbeveiliging voor klimmen.",
    "Isoleren met steenwol.",
    "Aantrekken bouten met momentsleutel.",
    "Wachten op druktest van leidingen.",
    "Stroom uitschakelen met schakelaar.",
    "Leggen onderdakfolie op dak.",
    "Schroeven plaat met schroef.",
    "Monteren raam met kozijnhuls.",
    "Spuiten purschuim met pistool.",
    "Leggen worteldoek onder grind.",
    "Reinigen bekisting met perslucht.",
    "Gebruiken wapeningsnet in vloer.",
    "Snijden gips met mes.",
    "Bevestigen dakpan met stormhaak.",
    "Trekken kabel in VP-buis.",
    "Storten sokkel met beton.",
    "Monteren deur met scharnieren.",
    "Leggen drainbuis met filterdoek.",
    "Gebruiken schuurmachine.",
    "Schilderen met acrylverf.",
    "Bevestigen blikbeslag met popnagel.",
    "Leggen isolatieplaten onder vloer.",
    "Schroeven met accuschroefmachine.",
    "Monteren ventilatie met WTW-systeem.",
    "Gebruiken gehoorbescherming.",
    "Storten trap met wapening.",
    "Bevestigen lat met spijkerpistool.",
    "Leggen dakpan op dak.",
    "Trekken glasvezel met blaasbuis.",
    "Isoleren leidingen met leidingisolatie.",
    "Gebruiken ademhalingsbescherming.",
    "Monteren raamdorpel van blik.",
    "Snijden isolatie met isolatiemes.",
    "Leggen vloerverwarming met leidingen.",
    "Bevestigen dakgootblik met schroef.",
    "Storten kolom met beton.",
    "Gebruiken laser.",
    "Monteren brandwerende afdichting.",
    "Trekken aardkabel in grondbuis.",
    "Leggen dampremmende folie op dak.",
    "Bevestigen met spijkerpistool.",
    "Storten vloer met wapening.",
    "Gebruiken veiligheidsbril.",
    "Monteren deurstopper.",
    "Snijden blik met blikschaar.",
    "Leggen dränmat.",
    "Trekken kabel in buis.",
    "Isoleren zolder met steenwol.",
    "Bevestigen met schroef.",
    "Monteren sprinklerinstallatie.",
    "Gebruiken kniebeschermers.",
    "Storten randbalk met beton.",
    "Snijden gips met gipsschaar.",
    "Leggen dakbedekking.",
    "Trekken glasvezel met blaasmachine.",
    "Isoleren vloer met isolatieplaten.",
    "Bevestigen met spijker.",
    "Monteren raam met dorpel.",
    "Gebruiken schuurmachine.",
    "Storten fundering met beton.",
    "Snijden isolatie met mes.",
    "Leggen worteldoek onder split.",
    "Trekken kabel in buis.",
    "Monteren branddeur.",
    "Bevestigen met spijkerpistool.",
    "Storten trap met wapening.",
    "Gebruiken gehoorbescherming.",
    "Leggen dakpan.",
    "Trekken aardlekschakelaar.",
    "Isoleren muur met steenwol.",
    "Bevestigen met accuschroefmachine.",
    "Monteren WTW-unit.",
    "Snijden blik met knabbelschaar.",
    "Leggen drainbuis.",
    "Trekken glasvezel met trekveer.",
    "Storten kolom met beton.",
    "Gebruiken laser.",
    "Monteren brandwerende afdichting.",
    "Bevestigen met popnagelpistool.",
    "Leggen winddichte folie.",
    "Controleren moment met momentsleutel."
  ],
  "gb": [
    "We're pouring the slab with concrete tomorrow.",
    "Stud with timber.",
    "We're waiting on rebar.",
    "Skim with fine filler.",
    "Tea break with flask.",
    "Hard hat with chin strap.",
    "Kill the engine on the digger.",
    "Crane up plasterboard with crane.",
    "Mind the scaffold with tubes.",
    "Lay OSB on roof trusses.",
    "Pour screed.",
    "Stud with timber here.",
    "Concrete is too wet.",
    "Measure with laser.",
    "Fix OSB with nail gun.",
    "Lay battens behind plasterboard.",
    "Don't pull hard on extension lead.",
    "We take lunch with lunchbox.",
    "Who has my spirit level?",
    "Check fall arrest before climbing.",
    "Insulate with mineral wool.",
    "Torque bolts with torque wrench.",
    "Wait for pressure test on pipes.",
    "Switch off power with breaker.",
    "Lay underlay on roof.",
    "Screw sheet with screw.",
    "Fit window with frame fixings.",
    "Spray foam with gun.",
    "Lay geotextile under gravel.",
    "Clean formwork with air line.",
    "Use mesh in slab.",
    "Cut plasterboard with knife.",
    "Fix roof tile with storm clip.",
    "Pull cable in conduit.",
    "Pour footing with concrete.",
    "Fit door with hinges.",
    "Lay land drain with filter fabric.",
    "Use sander.",
    "Paint with acrylic paint.",
    "Fix flashing with rivet.",
    "Lay insulation under slab.",
    "Screw with cordless drill.",
    "Fit ventilation with HRV system.",
    "Use ear defenders.",
    "Pour stairs with rebar.",
    "Fix trim with pin gun.",
    "Lay roof tile on roof.",
    "Blow fibre with blowing tube.",
    "Insulate pipes with pipe insulation.",
    "Use respirator.",
    "Fit window cill with sheet metal.",
    "Cut insulation with insulation knife.",
    "Lay underfloor heating with pipes.",
    "Fix eaves sheet with screw.",
    "Pour column with concrete.",
    "Use laser.",
    "Fit firestop.",
    "Pull earth cable in duct.",
    "Lay vapour barrier on roof.",
    "Fix with nail gun.",
    "Pour floor with rebar.",
    "Use safety glasses.",
    "Fit door stop.",
    "Cut sheet with tin snips.",
    "Lay drainage mat.",
    "Pull cable in conduit.",
    "Insulate attic with mineral wool.",
    "Fix with screw.",
    "Fit sprinkler system.",
    "Use knee pads.",
    "Pour edge beam with concrete.",
    "Cut plasterboard with board saw.",
    "Lay roofing felt.",
    "Blow fibre with blowing machine.",
    "Insulate floor with insulation boards.",
    "Fix with pins.",
    "Fit window with cill.",
    "Use sander.",
    "Pour foundation with concrete.",
    "Cut insulation with knife.",
    "Lay geotextile under aggregate.",
    "Pull cable in conduit.",
    "Fit fire door.",
    "Fix with nail gun.",
    "Pour stairs with rebar.",
    "Use ear defenders.",
    "Lay roof tile.",
    "Pull RCD.",
    "Insulate wall with mineral wool.",
    "Fix with cordless drill.",
    "Fit HRV unit.",
    "Cut sheet with nibbler.",
    "Lay land drain.",
    "Pull fibre with fish tape.",
    "Pour column with concrete.",
    "Use laser.",
    "Fit firestop.",
    "Fix with rivet gun.",
    "Lay breather membrane.",
    "Check torque with torque wrench."
  ]
};
