const healthcareData = {
  "se": [
    "Vill du se på TV?",
    "Ska vi gå till köket?",
    "Vill du ha en promenad i rullstol?",
    "Vill du ha en promenad inomhus?",
    "Vill du ta en promenad?",
    "Vill du ha en saga?",
    "Vill du ha en saga?",
    "Tack för att jag fick vara hos dig idag.",
    "Hur känns det i fötterna?",
    "Hur känns det i fötterna?",
    "God morgon, hur mår du idag?",
    "Har du tagit din insulin?",
    "Jag kontrollerar blodsockret.",
    "Ska vi ringa till din dotter?",
    "Jag kontrollerar temperaturen.",
    "Jag kontrollerar temperaturen.",
    "Behöver du mer tid idag?",
    "Jag öppnar fönstret.",
    "Vill du ha en kaka?",
    "Vill du ha en glass?",
    "Vill du ha en kopp kakao?",
    "Vill du ha en glass?",
    "Hur känns det i kroppen?",
    "Hur känns det i bröstet?",
    "Hur känns hjärtat?",
    "Hur känns det i huvudet?",
    "Hur känns det i huvudet?",
    "Vill du ha en dusch?",
    "Jag hjälper dig med håret.",
    "Jag hjälper dig med håret.",
    "Jag kontrollerar blodtrycket.",
    "Jag kontrollerar pulsen.",
    "Har du kissat?",
    "Har du kissat på dig?",
    "Behöver du hjälp med toalettbesöket?",
    "Jag hjälper dig med tröjan.",
    "Jag hjälper dig med byxorna.",
    "Jag hjälper dig med tröjan.",
    "Vill du ha en kudde till?",
    "Vill du ha en filt?",
    "Jag hjälper dig till sängen.",
    "Jag hjälper dig till sängen.",
    "Har du hosta?",
    "Har du hosta?",
    "Hur känns magen?",
    "Hur känns det i magen?",
    "Jag hjälper dig upp ur stolen.",
    "Hur känns benen?",
    "Jag lägger fram kläderna.",
    "Jag hjälper dig med tandborsten.",
    "Jag hjälper dig med tandborsten.",
    "Jag tar fram frukosten.",
    "Har du ätit middag?",
    "Har du ätit lunch?",
    "Har du ätit frukost?",
    "Vill du ha en promenad i trädgården?",
    "Vill du ha en kram?",
    "Vill du ha en kram?",
    "Har du ätit frukt?",
    "Jag är här för att stötta dig.",
    "Jag hjälper dig med strumporna.",
    "Jag hjälper dig med skorna.",
    "Jag hjälper dig med strumporna.",
    "Jag hjälper dig med skorna.",
    "Jag hjälper dig med strumporna.",
    "Hur känns humöret?",
    "Berätta om din dag.",
    "Vill du gå på toaletten först?",
    "Hur är vädret ute?",
    "Låt oss planera veckans aktiviteter.",
    "Har du ont någonstans?",
    "Hur känns det i ryggen?",
    "Hur känns det i nacken?",
    "Har du tagit din smärtstillande?",
    "Hur känns det i axlarna?",
    "Vill du dricka kaffe med mig?",
    "Vill du ha en kopp kaffe?",
    "Vill du ha en kopp kaffe?",
    "Vill du lyssna på musik?",
    "Vill du ha något att läsa?",
    "Vill du ha en bok?",
    "Vill du ha en tidning?",
    "Jag hjälper dig med glasögonen.",
    "Jag hjälper dig med medicinen.",
    "Har du tagit din blodtrycksmedicin?",
    "Har du tagit din hjärtmedicin?",
    "Hur sover du på nätterna?",
    "Har du sovit bra?",
    "Vill du ha en filt?",
    "Jag stänger fönstret.",
    "Jag stänger dörren.",
    "Tack för idag!",
    "Jag hjälper dig med jackan.",
    "Du är viktig för oss.",
    "Vill du ha en kopp te?",
    "Vill du ha en filt över knäna?",
    "Vill du ha en kopp te med honung?",
    "Vill du ha en filt över knäna?",
    "Har du druckit vatten?",
    "Vill du ha en kopp saft?"
  ],
  "da": [
    "Vil du se fjernsyn?",
    "Skal vi gå ud i køkkenet?",
    "Vil du have en tur i kørestol?",
    "Vil du have en tur indendørs?",
    "Vil du have en tur indendørs?",
    "Vil du have en historie?",
    "Vil du have en historie?",
    "Tak fordi jeg måtte være hos dig i dag.",
    "Hvordan er fødderne?",
    "Hvordan er fødderne?",
    "Har du taget din insulin?",
    "Jeg tjekker blodsukkeret.",
    "Skal vi ringe til din søn?",
    "Jeg tjekker temperaturen.",
    "Jeg tjekker temperaturen.",
    "Jeg åbner vinduet.",
    "Er du sulten? Lad os spise sammen.",
    "Vil du have en kage?",
    "Vil du have en is?",
    "Vil du have en kop kakao?",
    "Vil du have en is?",
    "Hvordan er brystet?",
    "Hvordan er dit hjerte?",
    "Hvordan er hovedet?",
    "Hvordan er hovedet?",
    "Vil du have kaffe med mig?",
    "Vil du have en kop kaffe?",
    "Vil du have en kop kaffe?",
    "God morgen, hvordan har du det i dag?",
    "Vil du have brusebad?",
    "Jeg hjælper dig med håret.",
    "Jeg hjælper dig med håret.",
    "Jeg tjekker blodtrykket.",
    "Jeg tjekker pulsen.",
    "Har du været på toilettet?",
    "Har du tisset på dig?",
    "Vil du have hjælp til badet?",
    "Jeg hjælper dig med trøjen.",
    "Jeg hjælper dig med bukserne.",
    "Jeg hjælper dig med trøjen.",
    "Vil du have en pude til?",
    "Vil du have et tæppe?",
    "Jeg hjælper dig i seng.",
    "Jeg hjælper dig i seng.",
    "Har du hoste?",
    "Har du hoste?",
    "Hvordan har du det i maven?",
    "Hvordan er maven?",
    "Hvordan er maven?",
    "Jeg hjælper dig op af stolen.",
    "Hvordan er benene?",
    "Jeg lægger tøjet frem.",
    "Jeg hjælper dig med tandbørsten.",
    "Jeg hjælper dig med tandbørsten.",
    "Jeg henter morgenmaden.",
    "Har du spist aftensmad?",
    "Har du spist frokost?",
    "Vil du gå en tur i haven?",
    "Vil du have en tur i haven?",
    "Vil du have et knus?",
    "Vil du have et knus?",
    "Har du spist frugt?",
    "Har du spist frugt?",
    "Jeg hjælper dig med sokkerne.",
    "Jeg hjælper dig med skoene.",
    "Jeg hjælper dig med sokkerne.",
    "Jeg hjælper dig med skoene.",
    "Jeg hjælper dig med sokkerne.",
    "Vil du på toilettet først?",
    "Fortæl mig om din dag.",
    "Hvordan er vejret i dag?",
    "Hvad kan jeg gøre for dig i dag?",
    "Har du ondt nogetsteds?",
    "Hvordan er ryggen?",
    "Hvordan er nakken?",
    "Har du taget din smertestillende?",
    "Hvordan er skuldrene?",
    "Vil du have noget at læse?",
    "Vil du have en bog?",
    "Vil du have en avis?",
    "Jeg er her for dig.",
    "Jeg hjælper dig med brillerne.",
    "Jeg hjælper dig med brillerne.",
    "Har du taget dine medicin?",
    "Har du taget din blodtryksmedicin?",
    "Har du taget din hjertemedicin?",
    "Har du sovet godt?",
    "Vil du have et tæppe?",
    "Jeg lukker vinduet.",
    "Jeg lukker døren.",
    "Jeg hjælper dig med jakken.",
    "Hvordan sover du om natten?",
    "Du er vigtig for os.",
    "Vil du have en kop te?",
    "Vil du have et tæppe over knæene?",
    "Vil du have te med honning?",
    "Vil du have et tæppe over knæene?",
    "Vil du have te med honning?",
    "Har du drukket vand?",
    "Vil du have en kop saft?"
  ],
  "no": [
    "Vil du ta en spasertur?",
    "Vil du se på TV?",
    "Skal vi gå til kjøkkenet?",
    "Vil du ha en tur i rullestol?",
    "Vil du ha en tur innendørs?",
    "Vil du ha en historie?",
    "Vil du ha en historie?",
    "Takk for at jeg fikk være hos deg i dag.",
    "Hvordan er føttene?",
    "Hvordan er føttene?",
    "Har du tatt insulinet?",
    "Jeg måler blodsukkeret.",
    "God morgen, hvordan går det?",
    "Skal vi ringe datteren din?",
    "Jeg måler temperaturen.",
    "Jeg måler temperaturen.",
    "Trenger du mer tid i dag?",
    "Jeg åpner vinduet.",
    "Vil du ha en kake?",
    "Vil du ha en is?",
    "Vil du ha en kopp kakao?",
    "Vil du ha en is?",
    "Hvordan føler du deg i dag?",
    "Hvordan er brystet?",
    "Hvordan er hjertet?",
    "Hvordan er hodet?",
    "Hvordan er hodet?",
    "Vil du ha dusj?",
    "Jeg hjelper deg med håret.",
    "Jeg hjelper deg med håret.",
    "Jeg måler blodtrykket.",
    "Jeg måler pulsen.",
    "Har du vært på do?",
    "Har du tisset på deg?",
    "Du er viktig for oss.",
    "Jeg hjelper deg med genseren.",
    "Jeg hjelper deg med buksene.",
    "Jeg hjelper deg med genseren.",
    "Vil du ha en pute til?",
    "Vil du ha et pledd?",
    "Jeg hjelper deg i seng.",
    "Jeg hjelper deg i seng.",
    "Har du hoste?",
    "Har du hoste?",
    "Hvordan er magen?",
    "Hvordan er magen?",
    "Jeg hjelper deg opp fra stolen.",
    "Hvordan er beina?",
    "Jeg legger frem klærne.",
    "Jeg hjelper deg med tannbørsten.",
    "Jeg hjelper deg med tannbørsten.",
    "Har du spist frokost?",
    "Jeg henter frokosten.",
    "Har du spist middag?",
    "Har du spist lunsj?",
    "Vil du ha en tur i hagen?",
    "Vil du ha en klem?",
    "Vil du ha en klem?",
    "Har du spist frukt?",
    "Jeg er her for å støtte deg.",
    "Trenger du hjelp med toalettet?",
    "Jeg hjelper deg med sokkene.",
    "Jeg hjelper deg med skoene.",
    "Jeg hjelper deg med sokkene.",
    "Jeg hjelper deg med skoene.",
    "Jeg hjelper deg med sokkene.",
    "Hvordan er humøret?",
    "Fortell meg om dagen din.",
    "Vil du på do først?",
    "Hvordan er været ute?",
    "La oss planlegge uka.",
    "Har du vondt noe sted?",
    "Hvordan er ryggen?",
    "Hvordan er nakken?",
    "Har du tatt smertestillende?",
    "Hvordan er skuldrene?",
    "Vil du ha kaffe med meg?",
    "Vil du ha en kopp kaffe?",
    "Vil du ha en kopp kaffe?",
    "Vil du høre på musikk?",
    "Vil du ha noe å lese?",
    "Vil du ha en bok?",
    "Vil du ha en avis?",
    "Jeg hjelper deg med brillene.",
    "Jeg hjelper deg med medisinene.",
    "Har du tatt blodtrykksmedisinen?",
    "Har du tatt hjertemedisinen?",
    "Hvordan sover du?",
    "Har du sovet godt?",
    "Vil du ha et pledd?",
    "Jeg lukker vinduet.",
    "Jeg lukker døren.",
    "Takk for i dag!",
    "Jeg hjelper deg med jakken.",
    "Vil du ha en kopp te?",
    "Vil du ha et pledd over knærne?",
    "Vil du ha te med honning?",
    "Vil du ha et pledd over knærne?",
    "Har du drukket vann?",
    "Vil du ha en kopp saft?"
  ],
  "de": [
    "Wollen wir einen Spaziergang machen?",
    "Möchten Sie fernsehen?",
    "Gehen wir in die Küche?",
    "Möchten Sie einen Rollstuhlspaziergang?",
    "Möchten Sie einen Spaziergang drinnen?",
    "Möchten Sie einen Spaziergang drinnen?",
    "Möchten Sie eine Geschichte hören?",
    "Möchten Sie eine Geschichte hören?",
    "Vielen Dank, dass ich heute bei Ihnen sein durfte.",
    "Wie gehen die Füße?",
    "Wie gehen die Füße?",
    "Haben Sie Ihr Insulin gespritzt?",
    "Ich messe den Blutzucker.",
    "Sollen wir Ihre Tochter anrufen?",
    "Ich messe die Temperatur.",
    "Ich messe die Temperatur.",
    "Guten Morgen, Herr/Frau [Name]. Wie geht es Ihnen heute?",
    "Ich öffne das Fenster.",
    "Möchten Sie ein Stück Kuchen?",
    "Möchten Sie ein Eis?",
    "Möchten Sie eine Tasse Kakao?",
    "Möchten Sie ein Eis?",
    "Wie geht es Ihrer Brust?",
    "Wie geht es Ihrem Herzen?",
    "Wie geht es Ihrem Kopf?",
    "Wie geht es Ihrem Kopf?",
    "Möchten Sie duschen?",
    "Ich helfe Ihnen mit den Haaren.",
    "Ich helfe Ihnen mit den Haaren.",
    "Ich messe den Blutdruck.",
    "Ich messe den Puls.",
    "Waren Sie auf der Toilette?",
    "Haben Sie in die Windel gemacht?",
    "Möchten Sie Hilfe beim Waschen?",
    "Ich helfe Ihnen mit dem Pullover.",
    "Ich helfe Ihnen mit der Hose.",
    "Ich helfe Ihnen mit dem Pullover.",
    "Möchten Sie ein weiteres Kissen?",
    "Möchten Sie eine Decke?",
    "Ich helfe Ihnen ins Bett.",
    "Ich helfe Ihnen ins Bett.",
    "Haben Sie Husten?",
    "Haben Sie Husten?",
    "Wie geht es Ihrem Magen?",
    "Wie geht es Ihrem Magen?",
    "Wie geht es Ihrem Magen?",
    "Ich helfe Ihnen aus dem Sessel.",
    "Wie geht es Ihren Beinen?",
    "Ich lege die Kleidung bereit.",
    "Ich helfe Ihnen mit der Zahnbürste.",
    "Ich helfe Ihnen mit der Zahnbürste.",
    "Ich hole das Frühstück.",
    "Haben Sie zu Abend gegessen?",
    "Haben Sie zu Mittag gegessen?",
    "Möchten Sie einen Spaziergang im Garten?",
    "Möchten Sie eine Umarmung?",
    "Möchten Sie eine Umarmung?",
    "Haben Sie Obst gegessen?",
    "Haben Sie Obst gegessen?",
    "Ich helfe Ihnen mit den Socken.",
    "Ich helfe Ihnen mit den Schuhen.",
    "Ich helfe Ihnen mit den Socken.",
    "Ich helfe Ihnen mit den Schuhen.",
    "Ich helfe Ihnen mit den Socken.",
    "Erzählen Sie mir von Ihrem Tag.",
    "Möchten Sie zuerst auf die Toilette?",
    "Wie ist das Wetter heute?",
    "Was kann ich heute für Sie tun?",
    "Haben Sie Schmerzen?",
    "Wie geht es Ihrem Rücken?",
    "Wie geht es Ihrem Nacken?",
    "Haben Sie Ihre Schmerztablette genommen?",
    "Wie gehen die Schultern?",
    "Möchten Sie Kaffee mit mir trinken?",
    "Möchten Sie eine Tasse Kaffee?",
    "Möchten Sie eine Tasse Kaffee?",
    "Möchten Sie etwas lesen?",
    "Möchten Sie ein Buch?",
    "Möchten Sie eine Zeitung?",
    "Haben Sie Ihre Medikamente eingenommen?",
    "Ich bin für Sie da.",
    "Ich helfe Ihnen mit der Brille.",
    "Ich helfe Ihnen mit der Brille.",
    "Haben Sie Ihre Blutdrucktablette genommen?",
    "Haben Sie Ihre Herztablette genommen?",
    "Haben Sie gut geschlafen?",
    "Möchten Sie eine Decke?",
    "Ich schließe das Fenster.",
    "Ich schließe die Tür.",
    "Ich helfe Ihnen mit der Jacke.",
    "Was möchten Sie zum Mittagessen?",
    "Wie haben Sie geschlafen?",
    "Sie sind wichtig für uns.",
    "Möchten Sie eine Tasse Tee?",
    "Möchten Sie eine Decke über die Knie?",
    "Möchten Sie Tee mit Honig?",
    "Möchten Sie eine Decke über die Knie?",
    "Möchten Sie Tee mit Honig?",
    "Haben Sie genug getrunken?",
    "Möchten Sie ein Glas Saft?"
  ],
  "nl": [
    "Zullen we een wandeling maken?",
    "Wilt u televisie kijken?",
    "Gaan we naar de keuken?",
    "Wilt u een rolstoelwandeling?",
    "Wilt u een wandeling binnenshuis?",
    "Wilt u een wandeling binnenshuis?",
    "Wilt u een verhaal horen?",
    "Wilt u een verhaal horen?",
    "Dank u wel dat ik vandaag bij u mocht zijn.",
    "Hoe zijn uw voeten?",
    "Hoe zijn uw voeten?",
    "Heeft u uw insuline gespoten?",
    "Ik meet de bloedsuiker.",
    "Zullen we uw dochter bellen?",
    "Ik meet de temperatuur.",
    "Ik meet de temperatuur.",
    "Ik open het raam.",
    "Wilt u een koekje?",
    "Wilt u een ijsje?",
    "Wilt u een kopje cacao?",
    "Wilt u een ijsje?",
    "Hoe is uw borst?",
    "Hoe is uw hart?",
    "Hoe is uw hoofd?",
    "Hoe is uw hoofd?",
    "Wilt u douchen?",
    "Ik help u met het haar.",
    "Ik help u met het haar.",
    "Ik meet de bloeddruk.",
    "Ik meet de pols.",
    "Bent u naar het toilet geweest?",
    "Heeft u in de luier geplast?",
    "Wilt u hulp bij het wassen?",
    "Ik help u met de trui.",
    "Ik help u met de broek.",
    "Ik help u met de trui.",
    "Wilt u een extra kussen?",
    "Wilt u een deken?",
    "Ik help u naar bed.",
    "Ik help u naar bed.",
    "Heeft u hoest?",
    "Heeft u hoest?",
    "Hoe is uw maag?",
    "Hoe is uw maag?",
    "Hoe is uw maag?",
    "Ik help u uit de stoel.",
    "Hoe zijn uw benen?",
    "Ik leg de kleding klaar.",
    "Ik help u met de tandenborstel.",
    "Ik help u met de tandenborstel.",
    "Ik haal het ontbijt.",
    "Heeft u avondeten gehad?",
    "Heeft u lunch gehad?",
    "Wilt u een wandeling in de tuin?",
    "Wilt u een knuffel?",
    "Wilt u een knuffel?",
    "Heeft u fruit gegeten?",
    "Heeft u fruit gegeten?",
    "Ik help u met de sokken.",
    "Ik help u met de schoenen.",
    "Ik help u met de sokken.",
    "Ik help u met de schoenen.",
    "Ik help u met de sokken.",
    "Vertel me over uw dag.",
    "Wilt u eerst naar het toilet?",
    "Hoe is het weer vandaag?",
    "Wat kan ik vandaag doen?",
    "Heeft u pijn ergens?",
    "Hoe is uw rug?",
    "Hoe is uw nek?",
    "Heeft u uw pijnstiller ingenomen?",
    "Hoe zijn uw schouders?",
    "Wilt u koffie met mij drinken?",
    "Wilt u een kopje koffie?",
    "Wilt u een kopje koffie?",
    "Wilt u iets lezen?",
    "Wilt u een boek?",
    "Wilt u een krant?",
    "Ik ben er voor u.",
    "Ik help u met de bril.",
    "Ik help u met de bril.",
    "Heeft u uw medicijnen ingenomen?",
    "Heeft u uw bloeddrukpil ingenomen?",
    "Heeft u uw hartpil ingenomen?",
    "Heeft u goed geslapen?",
    "Wilt u een deken?",
    "Ik sluit het raam.",
    "Ik sluit de deur.",
    "Ik help u met de jas.",
    "Wat wilt u eten?",
    "Hoe slaapt u 's nachts?",
    "Goedemorgen, hoe voelt u zich vandaag?",
    "U bent belangrijk voor ons.",
    "Wilt u een kopje thee?",
    "Wilt u een deken over de knieën?",
    "Wilt u thee met honing?",
    "Wilt u een deken over de knieën?",
    "Wilt u thee met honing?",
    "Heeft u genoeg gedronken?",
    "Wilt u een glas sap?"
  ],
  "gb": [
    "Shall we go for a walk?",
    "Would you like to watch TV?",
    "Shall we go to the kitchen?",
    "Would you like a wheelchair walk?",
    "Would you like a walk indoors?",
    "Would you like a walk indoors?",
    "Would you like a story?",
    "Would you like a story?",
    "Thank you for letting me be with you today.",
    "How are your feet?",
    "How are your feet?",
    "Have you had your insulin?",
    "I'll check your blood sugar.",
    "Shall we call your daughter?",
    "I'll take your temperature.",
    "I'll take your temperature.",
    "I'll open the window.",
    "Would you like a biscuit?",
    "Would you like an ice cream?",
    "Would you like a cup of cocoa?",
    "Would you like an ice cream?",
    "How is your chest?",
    "How is your heart?",
    "How is your head?",
    "How is your head?",
    "Would you like a shower?",
    "I'll help you with your hair.",
    "I'll help you with your hair.",
    "I'll check your blood pressure.",
    "I'll check your pulse.",
    "Have you been to the toilet?",
    "Have you wet yourself?",
    "Would you like help with washing?",
    "I'll help you with your jumper.",
    "I'll help you with your trousers.",
    "I'll help you with your jumper.",
    "Would you like another pillow?",
    "Would you like a blanket?",
    "I'll help you to bed.",
    "I'll help you to bed.",
    "Do you have a cough?",
    "Do you have a cough?",
    "How is your tummy?",
    "How is your tummy?",
    "How is your tummy?",
    "I'll help you out of the chair.",
    "How are your legs?",
    "I'll lay out your clothes.",
    "I'll help you with your toothbrush.",
    "I'll help you with your toothbrush.",
    "I'll get your breakfast.",
    "Have you had dinner?",
    "Have you had lunch?",
    "Would you like a walk in the garden?",
    "Would you like a hug?",
    "Would you like a hug?",
    "Have you eaten fruit?",
    "Have you eaten fruit?",
    "Good morning, how are you feeling today?",
    "I'll help you with your socks.",
    "I'll help you with your shoes.",
    "I'll help you with your socks.",
    "I'll help you with your shoes.",
    "I'll help you with your socks.",
    "Tell me about your day.",
    "Would you like the toilet first?",
    "How's the weather today?",
    "What can I do for you today?",
    "Are you in any pain?",
    "How is your back?",
    "How is your neck?",
    "Have you taken your painkiller?",
    "How are your shoulders?",
    "Would you like a cup of tea with me?",
    "Would you like a cup of coffee?",
    "Would you like a cup of coffee?",
    "Would you like something to read?",
    "Would you like a book?",
    "Would you like a newspaper?",
    "I'm here to support you.",
    "I'll help you with your glasses.",
    "I'll help you with your glasses.",
    "Have you taken your medication?",
    "Have you taken your blood pressure tablet?",
    "Have you taken your heart tablet?",
    "Did you sleep well?",
    "Would you like a blanket?",
    "I'll close the window.",
    "I'll close the door.",
    "I'll help you with your coat.",
    "What would you like for lunch?",
    "How did you sleep last night?",
    "You are important to us.",
    "Would you like a cup of tea?",
    "Would you like a blanket over your knees?",
    "Would you like tea with honey?",
    "Would you like a blanket over your knees?",
    "Would you like tea with honey?",
    "Have you had enough to drink?",
    "Would you like a glass of juice?"
  ]
};
