const horecaData = {
  "se": [
    "Hej!",
    "God morgon!",
    "Välkommen!",
    "Vad kan jag hjälpa dig med?",
    "Har du bestämt dig?",
    "Vad vill du beställa?",
    "En kopp kaffe, tack.",
    "Smaklig måltid!",
    "Tack för besöket!",
    "Får jag ta din beställning?",
    "Varsågod, här är menyn.",
    "Vill du ha något att dricka?",
    "Faktura, tack.",
    "Tack så mycket!",
    "Ha en trevlig dag!",
    "Ursäkta, var är toaletten?",
    "Kan jag få en bordsreservning?",
    "Vi har dagens lunch för 99 kronor.",
    "Bullar till fikan?",
    "Kaffemaskin",
    "Bestick",
    "Servett",
    "Tallrik",
    "Glas",
    "Meny",
    "Kassa",
    "Kortterminal",
    "Etikett",
    "Hylla",
    "Varukorg",
    "Hej, välkommen in!",
    "Hur mycket kostar det?",
    "Har ni det i storlek M?",
    "Kan jag få en påse?",
    "Det är rea idag.",
    "Tack för ditt köp!",
    "Behöver du hjälp med något?",
    "Var hittar jag mjölken?",
    "Det blir 150 kronor totalt.",
    "Välkommen tillbaka!",
    "Lagom portioner, tack.",
    "Fika-paus?",
    "Dagens special: smörgås.",
    "Allergivänlig meny?",
    "Bord för två, tack.",
    "Räkning, snälla.",
    "Trevligt att ses!",
    "Kan du värma upp det?",
    "Nybryggt kaffe.",
    "Diskmaskin",
    "Kylskåp",
    "Mixer",
    "Våtservetter",
    "Plastpåse",
    "Kläderställ",
    "Kassakvitto",
    "Prislapp",
    "Kundvagn",
    "Ursäkta, det här passar inte.",
    "Kan jag byta varan?",
    "Rabattkupon?",
    "Öppet till 20:00.",
    "Stängt för inventering.",
    "Välkommen till butiken!",
    "Vad letar du efter?",
    "Det här är populärt.",
    "Prova på!",
    "Passar perfekt.",
    "Hotelcheck-in.",
    "Rum för natten.",
    "Nyckelkort",
    "Handduk",
    "Sängkläder",
    "Frukostbuffé",
    "Concierge",
    "Parkering",
    "WiFi-lösenord",
    "Städtjänst",
    "Kundservice",
    "Returpolicy",
    "Garanti",
    "Lager",
    "Förpackning",
    "Etikettmaskin",
    "Scanner",
    "Vägskål",
    "Kylbox",
    "Korg",
    "Hej igen!",
    "Nöjd kund?",
    "Feedback tack.",
    "Lojalitetskort",
    "Kampanj",
    "Nyheter i sortimentet.",
    "Håll"
  ],
  "da": [
    "Hej!",
    "God morgen!",
    "Velkommen!",
    "Hvad kan jeg hjælpe dig med?",
    "Har du valgt?",
    "Hvad vil du bestille?",
    "En kop kaffe, tak.",
    "Velbekomme!",
    "Tak for i dag!",
    "Må jeg tage jeres bestilling?",
    "Her er menuen.",
    "Vil du have noget at drikke?",
    "Regningen, tak.",
    "Mange tak!",
    "Hav en hyggelig dag!",
    "Undskyld, hvor er toilettet?",
    "Kan jeg reservere et bord?",
    "Dagens frokost er 99 kr.",
    "Hygge med boller?",
    "Kaffemaskine",
    "Bestik",
    "Serviet",
    "Tallerken",
    "Glas",
    "Menu",
    "Kasse",
    "Kortterminal",
    "Prismetke",
    "Hylde",
    "Indkøbskurv",
    "Hej, kom ind!",
    "Hvor meget koster det?",
    "Har I det i størrelse M?",
    "Kan jeg få en pose?",
    "Det er tilbud i dag.",
    "Tak for købet!",
    "Har du brug for hjælp?",
    "Hvor finder jeg mælken?",
    "Det bliver 150 kr. totalt.",
    "Velkommen tilbage!",
    "Hygge-portioner, tak.",
    "Hygge-pause?",
    "Dagens special: smørrebrød.",
    "Allergivenlig menu?",
    "Bord til to, tak.",
    "Regning, venligst.",
    "Hyggeligt at møde dig!",
    "Kan du varme det op?",
    "Nybrygget kaffe.",
    "Køkken",
    "Opvaskemaskine",
    "Køleskab",
    "Ovnen",
    "Blender",
    "Fugtige servietter",
    "Plastpose",
    "Tøjstativ",
    "Kvitto",
    "Prislabel",
    "Indkøbsvogn",
    "Undskyld, det passer ikke.",
    "Kan jeg bytte varen?",
    "Rabatkupon?",
    "Åbent til 20:00.",
    "Lukket for lageroprydning.",
    "Velkommen til butikken!",
    "Hvad leder du efter?",
    "Det her er populært.",
    "Prøv det på!",
    "Passer perfekt.",
    "Hotel-check-in.",
    "Værelse for natten.",
    "Nøglekort",
    "Håndklæde",
    "Sengetøj",
    "Morgenmadsbuffet",
    "Portier",
    "Parkering",
    "WiFi-kode",
    "Rengøringsservice",
    "Kundeservice",
    "Returpolitik",
    "Garanti",
    "Lager",
    "Emballage",
    "Etikettemaskine",
    "Scanner",
    "Vægt",
    "Kølebox",
    "Kurv",
    "Hej igen!",
    "Tilfreds kunde?",
    "Feedback, tak.",
    "Loyalitetskort",
    "Kampagne",
    "Nyheder i sortimentet.",
    "Bæredygtigt materiale.",
    "Økologisk kaffe.",
    "Hurtig levering.",
    "Tak for tilliden!"
  ],
  "no": [
    "Hei!",
    "God morgen!",
    "Velkommen!",
    "Hva kan jeg hjelpe deg med?",
    "Har du bestemt deg?",
    "Hva vil du bestille?",
    "En kopp kaffe, takk.",
    "Vel bekomme!",
    "Takk for besøket!",
    "Kan jeg ta bestillingen deres?",
    "Her er menyen.",
    "Vil du ha noe å drikke?",
    "Regningen, takk.",
    "Tusen takk!",
    "Ha en fin dag!",
    "Unnskyld, hvor er toalettet?",
    "Kan jeg reservere bord?",
    "Dagens lunsj er 99 kr.",
    "Koselig med boller?",
    "Kaffemaskin",
    "Bestikk",
    "Serviett",
    "Glass",
    "Meny",
    "Kasse",
    "Kortterminal",
    "Prismerking",
    "Hylle",
    "Handlekurv",
    "Hei, velkommen inn!",
    "Hvor mye koster det?",
    "Har dere det i størrelse M?",
    "Kan jeg få en pose?",
    "Det er salg i dag.",
    "Takk for kjøpet!",
    "Trenger du hjelp?",
    "Hvor finner jeg melken?",
    "Det blir 150 kr totalt.",
    "Velkommen tilbake!",
    "Koselige porsjoner, takk.",
    "Kos-pause?",
    "Dagens spesial: smørbrød.",
    "Allergivennlig meny?",
    "Bord for to, takk.",
    "Regning, vær så snill.",
    "Hyggelig å møte deg!",
    "Kan du varme det?",
    "Nybrent kaffe.",
    "Kjøkken",
    "Oppvaskmaskin",
    "Kjøleskap",
    "Ovnen",
    "Mikser",
    "Fuktige kluter",
    "Plastpose",
    "Klærstativ",
    "Kvittering",
    "Prislabel",
    "Handlekurv",
    "Unnskyld, det passer ikke.",
    "Kan jeg bytte varen?",
    "Rabattkupong?",
    "Åpent til 20:00.",
    "Stengt for inventar.",
    "Velkommen til butikken!",
    "Hva leter du etter?",
    "Dette er populært.",
    "Prøv det på!",
    "Passer perfekt.",
    "Hotell-innsjekking.",
    "Rom for natten.",
    "Nøkkelkort",
    "Håndkle",
    "Sengetøy",
    "Frokostbuffé",
    "Portner",
    "Parkering",
    "WiFi-passord",
    "Rengjøringstjeneste",
    "Kundeservice",
    "Returpolicy",
    "Garanti",
    "Lager",
    "Emballasje",
    "Etikettmaskin",
    "Skanner",
    "Vekt",
    "Kjølebox",
    "Kurv",
    "Hei igjen!",
    "Fornøyd kunde?",
    "Tilbakemelding, takk.",
    "Kundekort",
    "Kampanje",
    "Nyheter i sortimentet.",
    "Bærekraftig materiale.",
    "Økologisk kaffe.",
    "Rask levering.",
    "Takk for tilliten!"
  ],
  "de": [
    "Hallo!",
    "Guten Morgen!",
    "Willkommen!",
    "Womit kann ich Ihnen helfen?",
    "Haben Sie sich entschieden?",
    "Was möchten Sie bestellen?",
    "Eine Tasse Kaffee, bitte.",
    "Guten Appetit!",
    "Danke für Ihren Besuch!",
    "Darf ich Ihre Bestellung aufnehmen?",
    "Hier ist die Karte.",
    "Möchten Sie etwas trinken?",
    "Die Rechnung, bitte.",
    "Vielen Dank!",
    "Einen schönen Tag!",
    "Entschuldigung, wo ist die Toilette?",
    "Kann ich einen Tisch reservieren?",
    "Das Tagesmenü kostet 9,90 €.",
    "Mit Brezen zum Kaffee?",
    "Kaffeemaschine",
    "Besteck",
    "Serviette",
    "Teller",
    "Glas",
    "Speisekarte",
    "Kasse",
    "Kartenterminal",
    "Preisschild",
    "Regal",
    "Einkaufskorb",
    "Hallo, kommen Sie herein!",
    "Wie viel kostet das?",
    "Haben Sie das in Größe M?",
    "Kann ich eine Tüte haben?",
    "Heute ist Sale.",
    "Danke für den Einkauf!",
    "Brauchen Sie Hilfe?",
    "Wo finde ich die Milch?",
    "Insgesamt 15 €.",
    "Auf Wiedersehen!",
    "Ausgewogene Portionen, bitte.",
    "Kaffeepause?",
    "Tagesgericht: Schnitzel.",
    "Allergikerfreundliche Karte?",
    "Tisch für zwei, bitte.",
    "Rechnung, bitte.",
    "Schön, Sie zu treffen!",
    "Können Sie es aufwärmen?",
    "Frischer Kaffee.",
    "Küche",
    "Spülmaschine",
    "Kühlschrank",
    "Ofen",
    "Mixer",
    "Feuchttücher",
    "Plastiktüte",
    "Kleiderständer",
    "Beleg",
    "Preisetikett",
    "Einkaufswagen",
    "Entschuldigung, es passt nicht.",
    "Kann ich umtauschen?",
    "Rabattgutschein?",
    "Geöffnet bis 20:00.",
    "Geschlossen wegen Inventur.",
    "Willkommen im Laden!",
    "Was suchen Sie?",
    "Das ist beliebt.",
    "Probieren Sie es an!",
    "Passt perfekt.",
    "Hotel-Check-in.",
    "Zimmer für die Nacht.",
    "Schlüsselkarte",
    "Handtuch",
    "Bettwäsche",
    "Frühstücksbuffet",
    "Concierge",
    "Parkplatz",
    "WiFi-Passwort",
    "Reinigungsservice",
    "Kundenservice",
    "Rückgabebedingungen",
    "Garantie",
    "Lager",
    "Verpackung",
    "Etikettiermaschine",
    "Scanner",
    "Waage",
    "Kühlbox",
    "Korb",
    "Hallo nochmal!",
    "Zufriedener Kunde?",
    "Feedback, bitte.",
    "Kundenkarte",
    "Aktion",
    "Neu im Sortiment.",
    "Nachhaltiges Material.",
    "Bio-Kaffee.",
    "Schnelle Lieferung.",
    "Danke für das Vertrauen!"
  ],
  "nl": [
    "Hallo!",
    "Goedemorgen!",
    "Welkom!",
    "Waarmee kan ik u helpen?",
    "Hebt u gekozen?",
    "Wat wilt u bestellen?",
    "Een kop koffie, alstublieft.",
    "Eet smakelijk!",
    "Dank voor uw bezoek!",
    "Mag ik uw bestelling opnemen?",
    "Hier is de menukaart.",
    "Wilt u iets drinken?",
    "De rekening, alstublieft.",
    "Hartelijk dank!",
    "Fijne dag!",
    "Pardon, waar is de wc?",
    "Kan ik een tafel reserveren?",
    "Het dagmenu kost 9,90 €.",
    "Met stroopwafels?",
    "Koffiemachine",
    "Bestek",
    "Servet",
    "Bord",
    "Glas",
    "Menu",
    "Kassa",
    "Pinapparaat",
    "Prijssticker",
    "Plank",
    "Winkelmandje",
    "Hallo, kom binnen!",
    "Hoeveel kost het?",
    "Hebt u het in maat M?",
    "Kan ik een tas hebben?",
    "Vandaag in de uitverkoop.",
    "Dank voor uw aankoop!",
    "Heeft u hulp nodig?",
    "Waar vind ik de melk?",
    "Totaal 15 €.",
    "Tot ziens!",
    "Matige porties, alstublieft.",
    "Koffiepauze?",
    "Dag special: erwtensoep.",
    "Allergievriendelijk menu?",
    "Tafel voor twee, alstublieft.",
    "Rekening, alsjeblieft.",
    "Leuk u te ontmoeten!",
    "Kunt u het opwarmen?",
    "Verse koffie.",
    "Keuken",
    "Afwasmachine",
    "Koelkast",
    "Oven",
    "Blender",
    "Natte doekjes",
    "Plastic tas",
    "Kledingrek",
    "Prijskaartje",
    "Winkelwagen",
    "Pardon, het past niet.",
    "Kan ik ruilen?",
    "Kortingbon?",
    "Open tot 20:00.",
    "Gesloten voor voorraad.",
    "Welkom in de winkel!",
    "Wat zoekt u?",
    "Dit is populair.",
    "Probeer het eens!",
    "Past perfect.",
    "Hotel-check-in.",
    "Kamer voor de nacht.",
    "Sleutelkaart",
    "Handdoek",
    "Beddengoed",
    "Ontbijtbuffet",
    "Conciërge",
    "Parkeerplaats",
    "WiFi-wachtwoord",
    "Schoonmaakdienst",
    "Klantenservice",
    "Retourbeleid",
    "Garantie",
    "Magazijn",
    "Verpakking",
    "Etikettenmachine",
    "Scanner",
    "Weegschaal",
    "Koelbox",
    "Mand",
    "Hallo weer!",
    "Tevreden klant?",
    "Feedback, alstublieft.",
    "Klantenkaart",
    "Actie",
    "Nieuw in het assortiment.",
    "Duurzaam materiaal.",
    "Biologische koffie.",
    "Snelle bezorging.",
    "Dank voor het vertrouwen!"
  ],
  "gb": [
    "Hello!",
    "Good morning!",
    "Welcome!",
    "How can I help you?",
    "Have you decided?",
    "What would you like to order?",
    "One cup of tea, please.",
    "Enjoy your meal!",
    "Thank you for visiting!",
    "May I take your order?",
    "Here's the menu.",
    "Would you like something to drink?",
    "The bill, please.",
    "Thank you very much!",
    "Have a great day!",
    "Excuse me, where's the loo?",
    "Can I book a table?",
    "Today's special is £9.90.",
    "Scones for tea?",
    "Coffee machine",
    "Cutlery",
    "Napkin",
    "Plate",
    "Glass",
    "Menu",
    "Till",
    "Card machine",
    "Price tag",
    "Shelf",
    "Shopping basket",
    "Hi, come in!",
    "How much is it?",
    "Do you have it in size M?",
    "Can I have a bag?",
    "It's on sale today.",
    "Thank you for shopping!",
    "Need any help?",
    "Where's the milk?",
    "That's £15 total.",
    "Cheerio!",
    "Balanced portions, please.",
    "Tea break?",
    "Today's special: fish and chips.",
    "Allergy-friendly menu?",
    "Table for two, please.",
    "Check, please.",
    "Nice to meet you!",
    "Can you warm it up?",
    "Fresh brew.",
    "Kitchen",
    "Dishwasher",
    "Fridge",
    "Oven",
    "Blender",
    "Wet wipes",
    "Plastic bag",
    "Clothes rail",
    "Receipt",
    "Price label",
    "Shopping trolley",
    "Excuse me, it doesn't fit.",
    "Can I exchange it?",
    "Discount voucher?",
    "Open until 8 PM.",
    "Closed for stocktake.",
    "Welcome to the shop!",
    "What are you looking for?",
    "This is popular.",
    "Try it on!",
    "Perfect fit.",
    "Hotel check-in.",
    "Room for the night.",
    "Key card",
    "Towel",
    "Bed linen",
    "Breakfast buffet",
    "Concierge",
    "Parking",
    "WiFi password",
    "Cleaning service",
    "Customer service",
    "Returns policy",
    "Warranty",
    "Warehouse",
    "Packaging",
    "Label machine",
    "Scanner",
    "Scales",
    "Cooler box",
    "Basket",
    "Hello again!",
    "Happy customer?",
    "Feedback, please.",
    "Loyalty card",
    "Promotion",
    "New in stock.",
    "Sustainable material.",
    "Organic tea.",
    "Quick delivery.",
    "Thanks for your custom!"
  ]
};
