const logisticsData = {
  "se": [
    "God morgon, välkommen till lagret",
    "Var är nästa leverans?",
    "Skanna varan in i systemet",
    "Pallen är redo för transport",
    "Kontrollera inventariet dagligen",
    "Använd skyddsutrustning alltid",
    "Plocka ordern från hyllan A3",
    "Förpacka varan säkert",
    "Uppdatera lagersaldot",
    "Trucken är under service",
    "Lasta av containern",
    "Etikettera paketet korrekt",
    "Genomför säkerhetsronde",
    "Beställ nytt material",
    "Registrera inkommande gods",
    "Optimera rutten för leverans",
    "Hantera returer snabbt",
    "Använd RFID-skanner",
    "Stäng av maskiner vid paus",
    "Planera skiftet i förväg",
    "Inspektera fordonet",
    "Arkivera dokumentation",
    "Koordinera med leverantören",
    "Minimera avfall i lagret",
    "Träna ny personal",
    "Overvaka temperaturen",
    "Paketera för export",
    "Uppfölj leveransstatus",
    "Byt ut defekt utrustning",
    "Rapportera avvikelser",
    "Organisera hyllorna alfabetiskt",
    "Verifiera kundorder",
    "Använd lyftanordning",
    "Underhåll verktyg regelbundet",
    "Kommunicera med teamet",
    "Fyll på förbrukningsmaterial",
    "Analysera lageromsättning",
    "Implementera lean-metoder",
    "Stämpel godkännande",
    "Planera lagerlayout",
    "Hämta varor från leverantör",
    "Registrera serienummer",
    "Genomför kvalitetskontroll",
    "Använd säkerhetsbälte i truck",
    "Uppdatera digitalt system",
    "Koordinera med retail-butik",
    "Hantera säsongsvariationer",
    "Etikett för farligt gods",
    "Optimera plockrut"
  ],
  "da": [
    "God morgen, velkommen til lageret",
    "Hvor er næste levering?",
    "Scan varen ind i systemet",
    "Pallen er klar til transport",
    "Tjek inventaret dagligt",
    "Brug sikkerhedsudstyr altid",
    "Pak ordrer fra hylden A3",
    "Pak varen sikkert",
    "Oppdater lagerbeholdningen",
    "Trucken er under vedligeholdelse",
    "Loss containere",
    "Mærk pakken korrekt",
    "Udfør sikkerhedsrunde",
    "Bestil nyt materiale",
    "Registrer indgående gods",
    "Optimér ruten for levering",
    "Håndter retur hurtigt",
    "Brug RFID-scanner",
    "Sluk maskiner ved pause",
    "Planlæg vagt i forvejen",
    "Inspektér køretøjet",
    "Arkivér dokumentation",
    "Koordinér med leverandøren",
    "Minimer affald på lageret",
    "Træn ny personale",
    "Overvåg temperaturen",
    "Pak til eksport",
    "Følg leveringsstatus",
    "Skift defekt udstyr",
    "Rapportér afvigelser",
    "Organisér hylderne alfabetisk",
    "Verificér kundeordre",
    "Brug liftanordning",
    "Vedligehold værktøj regelmæssigt",
    "Kommunikér med holdet",
    "Fyld på forbrugsvarer",
    "Analysér lageromsætning",
    "Implementér lean-metoder",
    "Stempel godkendelse",
    "Planlæg lagerlayout",
    "Hent varer fra leverandør",
    "Registrer serienummer",
    "Udfør kvalitetskontrol",
    "Brug sikkerhedsbælte i truck",
    "Oppdater digitalt system",
    "Koordinér med detailbutik",
    "Håndter sæsonvariationer",
    "Mærke for farligt gods",
    "Optimér plukrute",
    "Ryd gammelt lager",
    "Bestil paller og folie",
    "Træningsdag for sikkerhed",
    "Lad batteri i truck",
    "Arkivér leveringsnoter",
    "Verificér vægt og mål",
    "Brug ergonomiske værktøjer",
    "Planlæg nattevagt",
    "Forny lejeaftale for plads",
    "Inspektér emballage",
    "Rapportér KPI'er",
    "Organisér returzone",
    "Kommunikér ændringer",
    "Fyld på beskyttelsesbriller",
    "Analysér leveringsforsinkelser",
    "Implementér ESG-mål",
    "Luk døre efter brug",
    "Planlæg inventar",
    "Hent dokumenter fra kunde",
    "Registrer miljøpåvirkning",
    "Udfør brandøvelse",
    "Brug digital signatur",
    "Oppdater prislisteer",
    "Håndter kunde reklamationer",
    "Mærke for kølevarer",
    "Optimér indlæssning",
    "Ryd papirkurve",
    "Bestil nye hylder",
    "Træn i kundeservice",
    "Download rapport",
    "Arkivér e-fakturaer",
    "Verificér identitet",
    "Brug anti-statisk måtte",
    "Planlæg weekenddrift",
    "Forny certifikater",
    "Inspektér alarm",
    "Rapportér hændelser",
    "Organisér værktøjskasse",
    "Kommunikér via app",
    "Fyld på handsker",
    "Analysér omkostninger",
    "Implementér automatisering",
    "Stempel for godkendt levering",
    "Planlæg udvidelse",
    "Hent prøveeksemplarer",
    "Registrer aktiver",
    "Udfør revision",
    "Brug QR-kode",
    "Oppdater manualer",
    "Håndter leverandør aftaler",
    "Afslut vagt sikkert"
  ],
  "no": [
    "God morgen, velkommen til lageret",
    "Hvor er neste levering?",
    "Skann varen inn i systemet",
    "Pallen er klar for transport",
    "Sjekk inventaret daglig",
    "Bruk verneutstyr alltid",
    "Plukk ordren fra hyllen A3",
    "Pakk varen trygt",
    "Oppdater lagerbeholdningen",
    "Trucken er under service",
    "Loss containere",
    "Merk pakken korrekt",
    "Gjennomfør sikkerhetsrunde",
    "Bestill nytt materiale",
    "Registrer innkommende gods",
    "Optimaliser ruten for levering",
    "Håndter returer raskt",
    "Bruk RFID-skanner",
    "Slå av maskiner ved pause",
    "Planlegg skiftet på forhånd",
    "Inspekter kjøretøyet",
    "Arkiver dokumentasjon",
    "Koordiner med leverandøren",
    "Minimer avfall på lageret",
    "Trene ny personell",
    "Overvåk temperaturen",
    "Pakk for eksport",
    "Følg leveringsstatus",
    "Bytt ut defekt utstyr",
    "Rapporter avvikelser",
    "Organiser hyllene alfabetisk",
    "Verifiser kundeordre",
    "Bruk løfteanordning",
    "Vedlikehold verktøy regelmessig",
    "Kommuniser med teamet",
    "Fyll på forbruksvarer",
    "Analyser lageromsetning",
    "Implementer lean-metoder",
    "Stempel godkjenning",
    "Planlegg lagerlayout",
    "Hent varer fra leverandør",
    "Registrer serienummer",
    "Gjennomfør kvalitetskontroll",
    "Bruk sikkerhetsbelte i truck",
    "Oppdater digitalt system",
    "Koordiner med retail-butikk",
    "Håndter sesongvariasjoner",
    "Merking for farlig gods",
    "Optimaliser plukkrute",
    "Rens gammelt lager",
    "Bestill paller og folie",
    "Treningsdag for sikkerhet",
    "Lad batteri i truck",
    "Arkiver leveringsnoter",
    "Verifiser vekt og mål",
    "Bruk ergonomiske verktøy",
    "Planlegg nattskift",
    "Forny leieavtale for plass",
    "Inspekter emballasje",
    "Rapporter KPI-er",
    "Organiser retursone",
    "Kommuniser endringer",
    "Fyll på vernebriller",
    "Analyser leveringsforsinkelser",
    "Implementer ESG-mål",
    "Lukk dører etter bruk",
    "Planlegg inventar",
    "Hent dokumenter fra kunde",
    "Registrer miljøpåvirkning",
    "Gjennomfør brannøvelse",
    "Bruk digital signatur",
    "Oppdater prislisteer",
    "Håndter kunde reklamasjoner",
    "Merking for kjølevarer",
    "Optimaliser lasting",
    "Rens papirkurver",
    "Bestill nye hyller",
    "Trene i kundeservice",
    "Last ned rapport",
    "Arkiver e-fakturaer",
    "Verifiser identitet",
    "Bruk anti-statisk matte",
    "Planlegg helgedrift",
    "Forny sertifikater",
    "Inspekter alarm",
    "Rapporter hendelser",
    "Organiser verktøykasse",
    "Kommuniser via app",
    "Fyll på hansker",
    "Analyser kostnader",
    "Implementer automatisering",
    "Stempel for godkjent levering",
    "Planlegg utvidelse",
    "Hent prøveeksemplarer",
    "Registrer eiendeler",
    "Gjennomfør revisjon",
    "Bruk QR-kode",
    "Oppdater manualer",
    "Håndter leverandøravtaler",
    "Avslutt skiftet trygt"
  ],
  "de": [
    "Guten Morgen, willkommen im Lager",
    "Wo ist die nächste Lieferung?",
    "Scannen Sie die Ware ins System",
    "Die Palette ist transportbereit",
    "Überprüfen Sie das Inventar täglich",
    "Tragen Sie immer Schutzausrüstung",
    "Picken Sie die Bestellung aus Regal A3",
    "Verpacken Sie die Ware sicher",
    "Aktualisieren Sie den Lagerbestand",
    "Der Gabelstapler ist in Wartung",
    "Entladen Sie den Container",
    "Beschriftung das Paket korrekt",
    "Führen Sie Sicherheitsrunde durch",
    "Bestellen Sie neues Material",
    "Registrieren Sie eingehende Güter",
    "Optimieren Sie die Lieferroute",
    "Behandeln Sie Retouren schnell",
    "Verwenden Sie RFID-Scanner",
    "Schalten Sie Maschinen bei Pause aus",
    "Planen Sie den Schicht im Voraus",
    "Inspektion des Fahrzeugs",
    "Archivieren Sie Dokumentation",
    "Koordinieren Sie mit dem Lieferanten",
    "Minimieren Sie Abfall im Lager",
    "Schulen Sie neues Personal",
    "Überwachen Sie die Temperatur",
    "Verpacken für Export",
    "Folgen Sie Lieferstatus",
    "Ersetzen Sie defekte Ausrüstung",
    "Melden Sie Abweichungen",
    "Organisieren Sie Regale alphabetisch",
    "Verifizieren Sie Kundenauftrag",
    "Verwenden Sie Hebevorrichtung",
    "Wartung von Werkzeugen regelmäßig",
    "Kommunizieren Sie mit dem Team",
    "Nachfüllen Verbrauchsmaterial",
    "Analysieren Lagerumschlag",
    "Implementieren Lean-Methoden",
    "Stempel Genehmigung",
    "Planen Lagerlayout",
    "Holen Sie Waren vom Lieferanten",
    "Registrieren Seriennummer",
    "Führen Qualitätskontrolle durch",
    "Tragen Sie Sicherheitsgurt im Stapler",
    "Aktualisieren digitales System",
    "Koordinieren mit Einzelhandelsgeschäft",
    "Handhaben saisonale Schwankungen",
    "Etikett für gefährliche Güter",
    "Optimieren Pickroute",
    "Räumen altes Lager",
    "Bestellen Paletten und Folie",
    "Schulungstag für Sicherheit",
    "Laden Stapler-Akku",
    "Archivieren Liefernotizen",
    "Verifizieren Gewicht und Maße",
    "Verwenden ergonomische Werkzeuge",
    "Planen Nachtschicht",
    "Verlängern Mietvertrag für Raum",
    "Inspektion Verpackung",
    "Melden KPIs",
    "Organisieren Retourenzone",
    "Kommunizieren Änderungen",
    "Nachfüllen Schutzbrillen",
    "Analysieren Lieferverzögerungen",
    "Implementieren ESG-Ziele",
    "Schließen Türen nach Gebrauch",
    "Planen Inventur",
    "Holen Dokumente vom Kunden",
    "Registrieren Umweltauswirkungen",
    "Führen Brandschutzübung durch",
    "Verwenden digitale Signatur",
    "Aktualisieren Preise",
    "Handhaben Kundenreklamationen",
    "Etikett für Kühlwaren",
    "Optimieren Beladung",
    "Entleeren Papierkörbe",
    "Bestellen neue Regale",
    "Schulen Kundenservice",
    "Herunterladen Bericht",
    "Archivieren E-Rechnungen",
    "Verifizieren Identität",
    "Verwenden antistatische Matte",
    "Planen Wochenendbetrieb",
    "Verlängern Zertifikate",
    "Inspektion Alarm",
    "Melden Vorfälle",
    "Organisieren Werkzeugwagen",
    "Kommunizieren via App",
    "Nachfüllen Handschuhe",
    "Analysieren Kosten",
    "Implementieren Automatisierung",
    "Stempel für genehmigte Lieferung",
    "Planen Erweiterung",
    "Holen Muster",
    "Registrieren Vermögenswerte",
    "Führen Revision durch",
    "Verwenden QR-Code",
    "Aktualisieren Handbücher",
    "Handhaben Lieferantverträge",
    "Beenden Schicht sicher"
  ],
  "nl": [
    "Goedemorgen, welkom in het magazijn",
    "Waar is de volgende levering?",
    "Scan de goederen in het systeem",
    "De pallet is klaar voor transport",
    "Controleer de voorraad dagelijks",
    "Draag altijd beschermende uitrusting",
    "Pak de order van plank A3",
    "Verpak de goederen veilig",
    "Werk de magazijnvoorraad bij",
    "De heftruck is in onderhoud",
    "Los de container",
    "Label het pakket correct",
    "Voer veiligheidsronde uit",
    "Bestel nieuw materiaal",
    "Registreer inkomende goederen",
    "Optimaliseer de leveringsroute",
    "Behandel retouren snel",
    "Gebruik RFID-scanner",
    "Zet machines uit tijdens pauze",
    "Plan de shift van tevoren",
    "Inspecteer het voertuig",
    "Archiveer documentatie",
    "Coördineer met de leverancier",
    "Minimaliseer afval in het magazijn",
    "Train nieuw personeel",
    "Monitor de temperatuur",
    "Verpak voor export",
    "Volg leveringsstatus",
    "Vervang defecte apparatuur",
    "Rapporteer afwijkingen",
    "Organiseer planken alfabetisch",
    "Verifieer klantorder",
    "Gebruik hefapparaat",
    "Onderhoud gereedschap regelmatig",
    "Communiceer met het team",
    "Vul verbruiksartikelen aan",
    "Analyseer magazijnomzet",
    "Implementeer lean-methoden",
    "Stempel goedkeuring",
    "Plan magazijnindeling",
    "Ha goederen op van leverancier",
    "Registreer serienummer",
    "Voer kwaliteitscontrole uit",
    "Draag veiligheidsgordel in heftruck",
    "Werk digitaal systeem bij",
    "Coördineer met retail-winkel",
    "Behandel seizoensvariaties",
    "Label voor gevaarlijke goederen",
    "Optimaliseer pickroute",
    "Ruim oud magazijn op",
    "Bestel pallets en folie",
    "Trainingsdag voor veiligheid",
    "Laad heftruck-accu",
    "Archiveer leveringsnotities",
    "Verifieer gewicht en afmetingen",
    "Gebruik ergonomische gereedschappen",
    "Plan nachtshift",
    "Verleng huurcontract voor ruimte",
    "Inspecteer verpakking",
    "Rapporteer KPI's",
    "Organiseer retourzone",
    "Communiceer wijzigingen",
    "Vul beschermbrillen aan",
    "Analyseer leveringsvertragingen",
    "Implementeer ESG-doelen",
    "Sluit deuren na gebruik",
    "Plan inventarisatie",
    "Ha documenten op van klant",
    "Registreer milieu-impact",
    "Voer brandoefening uit",
    "Gebruik digitale handtekening",
    "Werk prijslijsten bij",
    "Behandel klantklachten",
    "Label voor koelgoederen",
    "Optimaliseer belading",
    "Leeg prullenbakken",
    "Bestel nieuwe planken",
    "Train klantenservice",
    "Download rapport",
    "Archiveer e-facturen",
    "Verifieer identiteit",
    "Gebruik antistatische mat",
    "Plan weekendoperaties",
    "Verleng certificaten",
    "Inspecteer alarm",
    "Rapporteer incidenten",
    "Organiseer gereedschapskar",
    "Communiceer via app",
    "Vul handschoenen aan",
    "Analyseer kosten",
    "Implementeer automatisering",
    "Stempel voor goedgekeurde levering",
    "Plan uitbreiding",
    "Ha monsters op",
    "Registreer activa",
    "Voer audit uit",
    "Gebruik QR-code",
    "Werk handleidingen bij",
    "Behandel leveranciersovereenkomsten",
    "Beëindig shift veilig"
  ],
  "gb": [
    "Phrase",
    "Good morning, welcome to the warehouse",
    "Where is the next delivery?",
    "Scan the item into the system",
    "The pallet is ready for transport",
    "Check inventory daily",
    "Wear safety gear always",
    "Pick the order from shelf A3",
    "Package the item securely",
    "Update stock levels",
    "The forklift is under maintenance",
    "Unload the container",
    "Label the package correctly",
    "Conduct safety round",
    "Order new materials",
    "Register incoming goods",
    "Optimize delivery route",
    "Handle returns quickly",
    "Use RFID scanner",
    "Turn off machines during break",
    "Plan the shift in advance",
    "Inspect the vehicle",
    "Archive documentation",
    "Coordinate with supplier",
    "Minimize waste in warehouse",
    "Train new staff",
    "Monitor temperature",
    "Package for export",
    "Track delivery status",
    "Replace faulty equipment",
    "Report deviations",
    "Organize shelves alphabetically",
    "Verify customer order",
    "Use lifting device",
    "Maintain tools regularly",
    "Communicate with team",
    "Restock consumables",
    "Analyze stock turnover",
    "Implement lean methods",
    "Stamp approval",
    "Plan warehouse layout",
    "Collect goods from supplier",
    "Register serial number",
    "Perform quality control",
    "Wear seatbelt in forklift",
    "Update digital system",
    "Coordinate with retail shop",
    "Manage seasonal variations",
    "Label for hazardous goods",
    "Optimize pick route",
    "Clear old stock",
    "Order pallets and wrap",
    "Training day for safety",
    "Charge forklift battery",
    "Archive delivery notes",
    "Verify weight and dimensions",
    "Use ergonomic tools",
    "Plan night shift",
    "Renew lease for space",
    "Inspect packaging",
    "Report KPIs",
    "Organize returns zone",
    "Communicate changes",
    "Restock safety glasses",
    "Analyze delivery delays",
    "Implement ESG goals",
    "Close doors after use",
    "Plan stocktake",
    "Collect documents from customer",
    "Register environmental impact",
    "Conduct fire drill",
    "Use digital signature",
    "Update price lists",
    "Handle customer complaints",
    "Label for chilled goods",
    "Optimize loading",
    "Empty bins",
    "Order new shelves",
    "Train customer service",
    "Download report",
    "Archive e-invoices",
    "Verify identity",
    "Use anti-static mat",
    "Plan weekend operations",
    "Renew certificates",
    "Inspect alarm",
    "Report incidents",
    "Organize tool trolley",
    "Communicate via app",
    "Restock gloves",
    "Analyze costs",
    "Implement automation",
    "Stamp approved delivery",
    "Plan expansion",
    "Collect samples",
    "Register assets",
    "Conduct audit",
    "Use QR code",
    "Update manuals",
    "Handle supplier contracts"
  ]
};
