const manufacturingData = {
  "se": [
    "Verktyg & Utrustning",
    "Skruvdragare",
    "Vinkelslipmaskin",
    "Momentnyckel",
    "Borrmaskin",
    "Svetsmaskin",
    "CNC-fräs",
    "Mätband",
    "Vattenpass",
    "Hydraulpress",
    "Multimeter",
    "Kapmaskin",
    "Slipmaskin",
    "Lyftkran",
    "Pallvagn",
    "Skiftnyckel",
    "Hylsnyckel",
    "Laserskärare",
    "Tryckluftsdriven mutterdragare",
    "Kalibreringsinstrument",
    "Skyddsglasögon",
    "Material",
    "Kolstål",
    "Rostfritt stål",
    "Aluminiumlegering",
    "Kopparplåt",
    "Betong",
    "Träfiberskiva",
    "Epoxiharts",
    "Polyeten",
    "Gummitätning",
    "Glasfiber",
    "Ståltråd",
    "Galvaniserad plåt",
    "PVC-rör",
    "Isolermaterial",
    "Sandpapper",
    "Smörjolja",
    "Svetswire",
    "Skruv M8",
    "Mutter M10",
    "Bult M12",
    "Processer & Operationer",
    "Svetsa fogarna",
    "Borra hålet",
    "Fräsa spåret",
    "Montera ramen",
    "Applicera tätningsmedel",
    "Justera nivån",
    "Lasta materialet",
    "Kalibrera maskinen",
    "Testa trycket",
    "Rengöra ytan",
    "Måla komponenten",
    "Skruva fast",
    "Limma ihop",
    "Värmebehandla",
    "Polera ytan",
    "Pressa formen",
    "Stansa hålet",
    "Böja röret",
    "Slipa kanten",
    "Kontrollera måtten",
    "Kvalitet & Kontroll",
    "Kontrollera toleranserna",
    "Inspektera svetsningen",
    "Mät tjockleken",
    "Dokumentera avvikelsen",
    "Utföra provning",
    "Kalibrera mätinstrument",
    "Godkänna leveransen",
    "Registrera batchnummer",
    "Utföra visuell kontroll",
    "Mäta hårdhet",
    "Kontrollera ytjämnhet",
    "Provbelasta strukturen",
    "Utföra funktionsprov",
    "Mäta spänning",
    "Kontrollera täthet",
    "Jämföra med ritning",
    "Märk komponenten",
    "Skicka provexemplar",
    "Uppdatera kvalitetsplan",
    "Rapportera defekter",
    "Säkerhet & Underhåll",
    "Bär skyddsutrustning",
    "Stäng av maskinen",
    "Kontrollera jordning",
    "Rengör arbetsplatsen",
    "Utför riskbedömning",
    "Använd lyftredskap",
    "Kontrollera tryckkärl",
    "Smörj lager",
    "Byt filter",
    "Kontrollera nödbromsen",
    "Märk farligt område",
    "Utför daglig inspektion",
    "Lås utrustningen",
    "Kontrollera brandsläckare",
    "Använd hörselskydd"
  ],
  "no": [
    "Skruetrækker",
    "Vinkelsliber",
    "Momentnøgle",
    "Boremaskine",
    "Svejseapparat",
    "CNC-fræser",
    "Målebånd",
    "Vaterpas",
    "Hydraulikpresse",
    "Multimeter",
    "Kapskærer",
    "Slibemaskine",
    "Traverskran",
    "Palleløfter",
    "Skiftenøgle",
    "Topnøgle",
    "Laserskærer",
    "Trykluftsmuttertrækker",
    "Kalibreringsværktøj",
    "Beskyttelsesbriller",
    "Kulstofstål",
    "Rustfrit stål",
    "Aluminiumlegering",
    "Kobberplade",
    "Beton",
    "Træfiberplade",
    "Epoxyharpiks",
    "Polyethylen",
    "Gummipakning",
    "Glasfiber",
    "Ståltråd",
    "Galvaniseret plade",
    "PVC-rør",
    "Isolationsmateriale",
    "Slibepapir",
    "Smøreolie",
    "Svejsetråd",
    "Skrue M8",
    "Møtrik M10",
    "Bolt M12",
    "Svær samlingerne",
    "Bor hullet",
    "Fræs sporet",
    "Montér rammen",
    "Påfør fugemasse",
    "Juster niveauet",
    "Indlæs materialet",
    "Kalibrér maskinen",
    "Test trykket",
    "Rengør overfladen",
    "Mal komponenten",
    "Skru fast",
    "Lim sammen",
    "Varmbehandle",
    "Polér overfladen",
    "Pres formen",
    "Stans hullet",
    "Bøj røret",
    "Slib kanten",
    "Kontroller målene",
    "Kontroller tolerancerne",
    "Inspicer svejsningen",
    "Mål tykkelsen",
    "Dokumentér afvigelsen",
    "Udfør prøvning",
    "Kalibrér måleinstrument",
    "Godkend leverancen",
    "Registrer batch-nummer",
    "Udfør visuel kontrol",
    "Mål hårdhed",
    "Kontroller ruhed",
    "Belast strukturen",
    "Udfør funktionstest",
    "Mål spænding",
    "Kontroller tæthed",
    "Sammenlign med tegning",
    "Mærk komponenten",
    "Send prøve",
    "Opdater kvalitetsplan",
    "Rapporter defekter",
    "Bær beskyttelsesudstyr",
    "Sluk maskinen",
    "Kontroller jordforbindelse",
    "Rengør arbejdspladsen",
    "Udfør risikovurdering",
    "Brug løfteudstyr",
    "Kontroller trykbeholder",
    "Smør lejet",
    "Skift filter",
    "Kontroller nødstop",
    "Mærk fareområde",
    "Udfør daglig inspektion",
    "Lås udstyr",
    "Kontroller brandslukker",
    "Brug høreværn",
    "Rapporter ulykke",
    "Kontroller ventilation contestants",
    "Skift sliddele",
    "Dokumentér vedligehold",
    "Sluk strømmen"
  ],
  "da": [
    "Skrutrekker",
    "Vinkelsliper",
    "Momentnøkkel",
    "Bormaskin",
    "Sveiseapparat",
    "CNC-fres",
    "Målebånd",
    "Vaterpass",
    "Hydraulikkpresse",
    "Multimeter",
    "Kappesag",
    "Slipemaskin",
    "Traverskran",
    "Jekketralle",
    "Skiftenøkkel",
    "Pipe",
    "Laserskjærer",
    "Trykkluftmuttertrekker",
    "Kalibreringsverktøy",
    "Vernebriller"
  ],
  "de": [
    "Schraubendreher",
    "Winkelschleifer",
    "Drehmomentschlüssel",
    "Bohrmaschine",
    "Schweißgerät",
    "CNC-Fräse",
    "Maßband",
    "Wasserwaage",
    "Hydraulikpresse",
    "Multimeter",
    "Trennschleifer",
    "Schleifmaschine",
    "Hallenkran",
    "Hubwagen",
    "Schraubenschlüssel",
    "Steckschlüssel",
    "Laserschneider",
    "Druckluftschrauber",
    "Kalibrierwerkzeug",
    "Schutzbrille",
    "Kohlenstoffstahl",
    "Edelstahl",
    "Aluminiumlegierung",
    "Kupferblech",
    "Beton",
    "Holzfaserplatte",
    "Epoxidharz",
    "Polyethylen",
    "Gummidichtung",
    "Glasfaser",
    "Stahldraht",
    "Verzinktes Blech",
    "PVC-Rohr",
    "Dämmmaterial",
    "Schleifpapier",
    "Schmieröl",
    "Schweißdraht",
    "Schraube M8",
    "Mutter M10",
    "Bolzen M12",
    "Schweiße die Nähte",
    "Bohre das Loch",
    "Fräse die Nut",
    "Montiere den Rahmen",
    "Trage Dichtmasse auf",
    "Richte das Niveau aus",
    "Belade das Material",
    "Kalibriere die Maschine",
    "Teste den Druck",
    "Reinige die Oberfläche",
    "Lackiere das Bauteil",
    "Schraube fest",
    "Verklebe die Teile",
    "Wärmebehandle",
    "Poliere die Oberfläche",
    "Presse die Form",
    "Stanze das Loch",
    "Biege das Rohr",
    "Schleife die Kante",
    "Kontrolliere die Maße",
    "Prüfe die Toleranzen",
    "Inspiziere die Schweißnaht",
    "Miss die Dicke",
    "Dokumentiere die Abweichung",
    "Führe Prüfung durch",
    "Kalibriere das Messgerät",
    "Genehmige die Lieferung",
    "Registriere die Chargennummer",
    "Führe Sichtprüfung durch",
    "Miss die Härte",
    "Prüfe die Rauheit",
    "Belaste die Struktur",
    "Führe Funktionstest durch",
    "Miss die Spannung",
    "Prüfe die Dichtheit",
    "Vergleiche mit Zeichnung",
    "Kennzeichne das Bauteil",
    "Sende Muster",
    "Aktualisiere den Qualitätsplan",
    "Melde Mängel",
    "Trage Schutzausrüstung",
    "Schalte die Maschine ab",
    "Prüfe die Erdung",
    "Reinige den Arbeitsplatz",
    "Führe Gefährdungsbeurteilung durch",
    "Verwende Hebezeug",
    "Prüfe den Druckbehälter",
    "Schmiere das Lager",
    "Wechsle den Filter",
    "Prüfe den Not-Aus",
    "Markiere den Gefahrenbereich",
    "Führe tägliche Inspektion durch",
    "Verriegele die Anlage",
    "Prüfe den Feuerlöscher",
    "Trage Gehörschutz",
    "Melde den Unfall",
    "Prüfe die Belüftung",
    "Wechsle Verschleißteile",
    "Dokumentiere die Wartung",
    "Schalte den Strom aus"
  ],
  "nl": [
    "Gereedschap & Uitrusting",
    "Schroevendraaier",
    "Haakse slijper",
    "Momentsleutel",
    "Boormachine",
    "Lasapparaat",
    "CNC-frees",
    "Rolmaat",
    "Waterpas",
    "Hydraulische pers",
    "Multimeter",
    "Afkortzaag",
    "Slijpmachine",
    "Hallenkraan",
    "Palletwagen",
    "Steeksleutel",
    "Dopsleutel",
    "Lasersnijder",
    "Persluchtmoeraanzetter",
    "Kalibratie-instrument",
    "Veiligheidsbril",
    "Materialen",
    "Koolstofstaal",
    "Roestvast staal",
    "Aluminiumlegering",
    "Koperplaat",
    "Beton",
    "Houtvezelplaat",
    "Epoxyhars",
    "Polyethyleen",
    "Rubberafdichting",
    "Glasvezel",
    "Staaldraad",
    "Gegalvaniseerde plaat",
    "PVC-buis",
    "Isolatiemateriaal",
    "Schuurpapier",
    "Smeerolie",
    "Lasdraad",
    "Schroef M8",
    "Moer M10",
    "Bout M12",
    "Processen & Operaties",
    "Las de naden",
    "Boor het gat",
    "Frees de groef",
    "Monteer het frame",
    "Breng kit aan",
    "Stel het niveau in",
    "Laad het materiaal",
    "Kalibreer de machine",
    "Test de druk",
    "Reinig het oppervlak",
    "Verf de component",
    "Draai vast",
    "Lijm de delen",
    "Warmtebehandel",
    "Polijst het oppervlak",
    "Pers de mal",
    "Pons het gat",
    "Buig de buis",
    "Slijp de rand",
    "Controleer de afmetingen",
    "Kwaliteit & Controle",
    "Controleer de toleranties",
    "Inspecteer de las",
    "Meet de dikte",
    "Documenteer de afwijking",
    "Voer beproeving uit",
    "Kalibreer het meetinstrument",
    "Keur de levering goed",
    "Registreer het batchnummer",
    "Voer visuele inspectie uit",
    "Meet de hardheid",
    "Controleer de ruwheid",
    "Belast de constructie",
    "Voer functietest uit",
    "Meet de spanning",
    "Controleer de dichtheid",
    "Vergelijk met tekening",
    "Markeer de component",
    "Stuur monster",
    "Werk de kwaliteitsplan bij",
    "Meld defecten",
    "Veiligheid & Onderhoud",
    "Draag persoonlijke beschermingsmiddelen",
    "Zet de machine uit",
    "Controleer de aarding",
    "Reinig de werkplek",
    "Voer risicoanalyse uit",
    "Gebruik hijsmiddel",
    "Controleer drukvat",
    "Smeer het lager",
    "Vervang het filter",
    "Controleer de noodstop",
    "Markeer het gevaarlijke gebied",
    "Voer dagelijkse inspectie uit",
    "Vergrendel de installatie",
    "Controleer de brandblusser",
    "Draag gehoorbescherming"
  ],
  "gb": [
    "Tools & Equipment",
    "Screwdriver",
    "Angle grinder",
    "Torque wrench",
    "Drill",
    "Welding machine",
    "CNC mill",
    "Tape measure",
    "Spirit level",
    "Hydraulic press",
    "Multimeter",
    "Cut-off saw",
    "Bench grinder",
    "Overhead crane",
    "Pallet truck",
    "Adjustable spanner",
    "Socket set",
    "Laser cutter",
    "Pneumatic impact wrench",
    "Calibration gauge",
    "Safety goggles",
    "Materials",
    "Carbon steel",
    "Stainless steel",
    "Aluminium alloy",
    "Copper sheet",
    "Concrete",
    "Fibreboard",
    "Epoxy resin",
    "Polyethylene",
    "Rubber gasket",
    "Glass fibre",
    "Steel wire",
    "Galvanised sheet",
    "PVC pipe",
    "Insulation material",
    "Abrasive paper",
    "Lubricating oil",
    "Filler wire",
    "M8 screw",
    "M10 nut",
    "M12 bolt",
    "Processes & Operations",
    "Weld the joints",
    "Drill the hole",
    "Mill the slot",
    "Assemble the frame",
    "Apply sealant",
    "Level the base",
    "Load the material",
    "Calibrate the machine",
    "Pressure test the system",
    "Clean the surface",
    "Paint the component",
    "Tighten the screw",
    "Bond the panels",
    "Heat treat the part",
    "Polish the surface",
    "Press the form",
    "Punch the hole",
    "Bend the pipe",
    "Grind the edge",
    "Check the dimensions",
    "Quality & Control",
    "Check tolerances",
    "Inspect the weld",
    "Measure thickness",
    "Record the deviation",
    "Carry out testing",
    "Calibrate the gauge",
    "Approve the delivery",
    "Log the batch number",
    "Perform visual inspection",
    "Test hardness",
    "Check surface finish",
    "Load test the structure",
    "Run function test",
    "Measure voltage",
    "Check for leaks",
    "Compare to drawing",
    "Label the part",
    "Send sample for approval",
    "Update the control plan",
    "Report non-conformance",
    "Safety & Maintenance",
    "Wear PPE",
    "Isolate the machine",
    "Check earth bonding",
    "Clear the work area",
    "Complete risk assessment",
    "Use lifting equipment",
    "Inspect pressure vessel",
    "Lubricate bearings",
    "Replace air filter",
    "Test emergency stop",
    "Mark hazard zone",
    "Carry out daily checks",
    "Lock off energy sources",
    "Check fire extinguisher",
    "Wear hearing protection"
  ]
};
